server:
  port: 8080

vector-database:
  base-url: "http://localhost:8000"
  endpoints:
    image-based-search: "/api/image-based-search"
    text-based-search: "/api/text-based-search"

search:
  image:
    save-directory: "/home/leto/demo_mid"

spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: simvec_project@outlook.com
    password: simvec_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
